export const SOLUTION_HUB_DROP_DOWN_DATA = {
DROP_DOWN_DATA_FETCHING : "SOLUTION_HUB_DROP_DOWN_DATA.DROP_DOWN_DATA_FETCHING",
DROP_DOWN_DATA_FETCHED : "SOLUTION_HUB_DROP_DOWN_DATA.DROP_DOWN_DATA_FETCHED",
DROP_DOWN_DATA_FETCH_FAILED : "SOLUTION_HUB_DROP_DOWN_DATA.DROP_DOWN_DATA_FETCH_FAILED",
DROP_DOWN_DATA_RESET : "SOLUTION_HUB_DROP_DOWN_DATA.DROP_DOWN_DATA_RESET",
};
