export const MODULES_SIDE_PANEL_DATA = {
  MODAL_OPEN: "MODULES_SIDE_PANEL_DATA.MODAL_OPEN",
  MODAL_CLOSE: "MODULES_SIDE_PANEL_DATA.MODAL_CLOSE",
  MODAL_TOGGLE: "MODULES_SIDE_PANEL_DATA.MODAL_TOGGLE",
  TYPE_OF_WORK_ADDED: "MODULES_SIDE_PANEL_DATA.TYPE_OF_WORK_ADDED",
  TYPE_OF_WORK_REMOVED: "MODULES_SIDE_PANEL_DATA.TYPE_OF_WORK_REMOVED",
  TYPE_OF_WORK_RESET: "MODULES_SIDE_PANEL_DATA.TYPE_OF_WORK_RESET",
  WORK_PACKAGES_ADDED: "MODULES_SIDE_PANEL_DATA.WORK_PACKAGES_ADDED",
  WORK_PACKAGES_REMOVED: "MODULES_SIDE_PANEL_DATA.WORK_PACKAGES_REMOVED",
  WORK_PACKAGES_RESET: "MODULES_SIDE_PANEL_DATA.WORK_PACKAGES_RESET",
  PANEL_RESET: "MODULES_SIDE_PANEL_DATA.PANEL_RESET",
  ALL_RESET: "MODULES_SIDE_PANEL_DATA.ALL_RESET",

  EDIT_LOADED: "MODULES_SIDE_PANEL_DATA.EDIT_LOADED",
  SET_TOW_DISABLED: "MODULES_SIDE_PANEL_DATA.SET_TOW_DISABLED",
  SET_TOW_WP: "MODULES_SIDE_PANEL_DATA.SET_TOW_WP",
  GET_SOLUTION_HUB_DATA_FETCHING:
    "MODULES_SIDE_PANEL_DATA.GET_SOLUTION_HUB_DATA_FETCHING",
  GET_SOLUTION_HUB_DATA_FETCHED:
    "MODULES_SIDE_PANEL_DATA.GET_SOLUTION_HUB_DATA_FETCHED",
  GET_SOLUTION_HUB_DATA_FAILED:
    "MODULES_SIDE_PANEL_DATA.GET_SOLUTION_HUB_DATA_FAILED",
  GET_CLONE_SELECTED_TYPE_OF_WORK:
    "MODULES_SIDE_PANEL_DATA.GET_CLONE_SELECTED_TYPE_OF_WORK",
  TYPE_OF_WORK_DATA_FETCHING:
    "MODULES_SIDE_PANEL_DATA.TYPE_OF_WORK_DATA_FETCHING",
  TYPE_OF_WORK_DATA_FETCHED:
    "MODULES_SIDE_PANEL_DATA.TYPE_OF_WORK_DATA_FETCHED",
  TYPE_OF_WORK_DATA_FAILED: "MODULES_SIDE_PANEL_DATA.TYPE_OF_WORK_DATA_FAILED",
  TYPE_OF_WORK_CLONE_SAVE_FETCHING:
    "MODULES_SIDE_PANEL_DATA.TYPE_OF_WORK_CLONE_SAVE_FETCHING",
  TYPE_OF_WORK_CLONE_SAVE_FETCHED:
    "MODULES_SIDE_PANEL_DATA.TYPE_OF_WORK_CLONE_SAVE_FETCHED",
  TYPE_OF_WORK_CLONE_SAVE_FAILED:
    "MODULES_SIDE_PANEL_DATA.TYPE_OF_WORK_CLONE_SAVE_FAILED",
};
