export const DYNAMIC_FIELDS_DATA = {
API_FETCHING : "DYNAMIC_FIELDS_DATA.API_FETCHING",
API_FETCHED : "DYNAMIC_FIELDS_DATA.API_FETCHED",
API_FETCH_FAILED : "DYNAMIC_FIELDS_DATA.API_FETCH_FAILED",
API_RESET : "DYNAMIC_FIELDS_DATA.API_RESET",

SOW_TEMPLATE_FIELD_CHANGED : "DYNAMIC_FIELDS_DATA.SOW_TEMPLATE_FIELD_CHANGED",
};
