export const CUSTOM_MODULES_SIDE_PANEL_DATA = {
  CUSTOM_MODAL_OPEN: "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODAL_OPEN",
  CUSTOM_MODAL_TOGGLE: "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODAL_TOGGLE",
  CUSTOM_MODAL_CLOSE: "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODAL_CLOSE",
  CUSTOM_TYPE_OF_WORK_ADDED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_TYPE_OF_WORK_ADDED",
  CUSTOM_TYPE_OF_WORK_REMOVED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_TYPE_OF_WORK_REMOVED",
  CUSTOM_TYPE_OF_WORK_RESET:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_TYPE_OF_WORK_RESET",
  CUSTOM_WORK_PACKAGES_ADDED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_WORK_PACKAGES_ADDED",
  CUSTOM_WORK_PACKAGES_ADDING:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_WORK_PACKAGES_ADDING",
  CUSTOM_WORK_PACKAGES_ADD_COMPLETE:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_WORK_PACKAGES_ADD_COMPLETE",
  CUSTOM_WORK_PACKAGES_REMOVED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_WORK_PACKAGES_REMOVED",
  CUSTOM_WORK_PACKAGES_RESET:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_WORK_PACKAGES_RESET",
  CUSTOM_PANEL_RESET: "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_PANEL_RESET",
  CUSTOM_ALL_RESET: "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_ALL_RESET",

  CUSTOM_EDIT_LOADED: "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_EDIT_LOADED",
  CUSTOM_MODULES_DROPDOWN_FETCHING:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODULES_DROPDOWN_FETCHING",
  CUSTOM_MODULES_DROPDOWN_FETCHED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODULES_DROPDOWN_FETCHED",
  CUSTOM_MODULES_DROPDOWN_FAILED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODULES_DROPDOWN_FAILED",

  CUSTOM_MODULES_SUBMIT_FETCHING:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODULES_SUBMIT_FETCHING",
  CUSTOM_MODULES_SUBMIT_FETCHED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODULES_SUBMIT_FETCHED",
  CUSTOM_MODULES_SUBMIT_FAILED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODULES_SUBMIT_FAILED",
  CUSTOM_MODULES_SEARCH_FETCHED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODULES_SEARCH_FETCHED",
  CUSTOM_MODULES_DOMAIN_FETCHED:
    "CUSTOM_MODULES_SIDE_PANEL_DATA.CUSTOM_MODULES_DOMAIN_FETCHED",
  CUSTOM_MODULES_STATE_ADD:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_MODULES_STATE_ADD",
  CUSTOM_MODULES_STATE_REMOVE:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_MODULES_STATE_REMOVE",
  CUSTOM_MODULES_STATE_UPDATE:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_MODULES_STATE_UPDATE",
  CUSTOM_MODULES_NAME_CHANGE_SETTING:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_MODULES_NAME_CHANGE_SETTING",
  CUSTOM_MODULES_NAME_CHANGE_SET:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_MODULES_NAME_CHANGE_SET",
  CUSTOM_MODULES_NAME_CHANGE_SET_FAILED:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_MODULES_NAME_CHANGE_SET_FAILED",
  RESET_SUBMIT: "CUSTOM_MODULES_SIDE_PANEL.RESET_SUBMIT",

  SHOULD_LOAD_DYNAMIC_VALUE_CHANGED:
    "CUSTOM_MODULES_SIDE_PANEL.SHOULD_LOAD_DYNAMIC_VALUE_CHANGED",
  CUSTOM_CLONE_MAIN_MODULES_CLONE_FETCHING:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_CLONE_MAIN_MODULES_CLONE_FETCHING",
  CUSTOM_CLONE_MAIN_MODULES_CLONE_FETCHED:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_CLONE_MAIN_MODULES_CLONE_FETCHED",
  CUSTOM_CLONE_MAIN_MODULES_CLONE_FAILED:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_CLONE_MAIN_MODULES_CLONE_FAILED",

  CUSTOM_SUBMIT_MODULES_FETCHING:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_SUBMIT_MODULES_FETCHING",
  CUSTOM_SUBMIT_MODULES_FETCHED:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_SUBMIT_MODULES_FETCHED",
  CUSTOM_SUBMIT_MODULES_FAILED:
    "CUSTOM_MODULES_SIDE_PANEL.CUSTOM_SUBMIT_MODULES_FAILED",
};
