export const LOG_DATA_TYPE = {
  LOG_DATA_FETCHING: "LOG_DATA_TYPE.LOG_DATA_FETCHING",
  LOG_DATA_FETCHED: "LOG_DATA_TYPE.LOG_DATA_FETCHED",
  LOG_DATA_FETCH_FAILED: "LOG_DATA_TYPE.LOG_DATA_FETCH_FAILED",
  LOG_DATA_RESET: "LOG_DATA_TYPE.LOG_DATA_RESET",
  LATEST_DATA: "LOG_DATA_TYPE.LOG_LATEST_DATA",
};
