export const SOLUTION_HUB_DATA = {
FIELD_ADDED : "SOLUTION_HUB_DATA.FIELD_ADDED",
FIELD_REMOVED : "SOLUTION_HUB_DATA.FIELD_REMOVED",
FIELD_UPDATED : "SOLUTION_HUB_DATA.FIELD_UPDATED",
FIELDS_LOADED : "SOLUTION_HUB_DATA.FIELDS_LOADED",
FIELDS_RESET : "SOLUTION_HUB_DATA.FIELDS_RESET",
};
