export const MASTER_DROP_DOWN_DATA_ACTION_TYPES = {
  ALL_DROPDOWN_DATA_FETCHING:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.ALL_DROPDOWN_DATA_FETCHING",
  ALL_DROPDOWN_DATA_FETCHED:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.ALL_DROPDOWN_DATA_FETCHED",
  ALL_DROPDOWN_DATA_FAILED:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.ALL_DROPDOWN_DATA_FAILED",

  TEMPLATE_FIELD_FETCHING:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.TEMPLATE_FIELD_FETCHING",
  TEMPLATE_FIELD_FETCHED:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.TEMPLATE_FIELD_FETCHED",
  TEMPLATE_FIELD_FAILED:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.TEMPLATE_FIELD_FAILED",

  SECTION_DATA_FETCHING:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.SECTION_DATA_FETCHING",
  SECTION_DATA_FETCHED:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.SECTION_DATA_FETCHED",
  SECTION_DATA_FAILED: "MASTER_DROP_DOWN_DATA_ACTION_TYPES.SECTION_DATA_FAILED",

  SKU_LIST_FETCHING: "MASTER_DROP_DOWN_DATA_ACTION_TYPES.SKU_LIST_FETCHING",
  SKU_LIST_FETCHED: "MASTER_DROP_DOWN_DATA_ACTION_TYPES.SKU_LIST_FETCHED",
  SKU_LIST_FAILED: "MASTER_DROP_DOWN_DATA_ACTION_TYPES.SKU_LIST_FAILED",

  ALL_DROPDOWN_DATA_RESET:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.ALL_DROPDOWN_DATA_RESET",

  SAVE_PRODUCTLINE_DATA:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.SAVE_PRODUCTLINE_DATA",
  SECTION_DATA_VALUE_CHANGED:
    "MASTER_DROP_DOWN_DATA_ACTION_TYPES.SECTION_DATA_VALUE_CHANGED",
};
