export const SHARING_MODAL_DATA = {
  MODAL_OPEN: "SHARING_MODAL_DATA.MODAL_OPEN",
  MODAL_CLOSE: "SHARING_MODAL_DATA.MODAL_CLOSE",
  MODAL_TOGGLE: "SHARING_MODAL_DATA.MODAL_TOGGLE",

  SHARING_SIDE_PANEL_OPEN: "SHARING_MODAL_DATA.SHARING_SIDE_PANEL_OPEN",
  SHARING_SIDE_PANEL_CLOSE: "SHARING_MODAL_DATA.SHARING_SIDE_PANEL_CLOSE",
  SHARING_SIDE_PANEL_TOGGLE: "SHARING_MODAL_DATA.SHARING_SIDE_PANEL_TOGGLE",

  SHARING_RIGHTS_FETCHING: "SHARING_MODAL_DATA.SHARING_RIGHTS_FETCHING",
  SHARING_RIGHTS_FETCHED: "SHARING_MODAL_DATA.SHARING_RIGHTS_FETCHED",
  SHARING_RIGHTS_FAILED: "SHARING_MODAL_DATA.SHARING_RIGHTS_FAILED",

  SHARING_USERLIST_FETCHING: "SHARING_MODAL_DATA.SHARING_USERLIST_FETCHING",
  SHARING_USERLIST_FETCHED: "SHARING_MODAL_DATA.SHARING_USERLIST_FETCHED",
  SHARING_USERLIST_FAILED: "SHARING_MODAL_DATA.SHARING_USERLIST_FETCHING",
  SHARING_RIGHTS_SELECTED: "SHARING_MODAL_DATA.SHARING_RIGHTS_SELECTED",
  SHARING_MODAL_RESET: "SHARING_MODAL_DATA.SHARING_MODAL_RESET",

  SHARING_SOW_FETCHING: "SHARING_MODAL_DATA.SHARING_SOW_FETCHING",
  SHARING_SOW_FETCHED: "SHARING_MODAL_DATA.SHARING_SOW_FETCHED",
  SHARING_SOW_FAILED: "SHARING_MODAL_DATA.SHARING_SOW_FAILED",
  SHARING_SELECT_USER: "SHARING_MODAL_DATA.SHARING_SELECT_USER",
  SHARING_MODAL_SELECTED_ID: "SHARING_MODAL_DATA.SHARING_MODAL_SELECTED_ID",
  SHARING_SIDE_PANEL_DATA_APPEND:
    "SHARING_MODAL_DATA.SHARING_SIDE_PANEL_DATA_APPEND",

  SHARING_SIDE_PANEL_DATA_FETCHING:
    "SHARING_MODAL_DATA.SHARING_SIDE_PANEL_DATA_FETCHING",
  SHARING_SIDE_PANEL_DATA_FETCHED:
    "SHARING_MODAL_DATA.SHARING_SIDE_PANEL_DATA_FETCHED",
  SHARING_SIDE_PANEL_DATA_FAILED:
    "SHARING_MODAL_DATA.SHARING_SIDE_PANEL_DATA_FAILED",
  SHARING_SIDE_PANEL_DATA_SEARCH:
    "SHARING_MODAL_DATA.SHARING_SIDE_PANEL_DATA_SEARCH",
  RESET_SIDEPANEL_DATA: "SHARING_MODAL_DATA.RESET_SIDEPANEL_DATA",
  SOW_VERSIONS_FETCHING: "SHARING_MODAL_DATA.SOW_VERSIONS_FETCHING",
  SOW_VERSIONS_FETCHED: "SHARING_MODAL_DATA.SOW_VERSIONS_FETCHED",
  SOW_VERSIONS_FAILED: "SHARING_MODAL_DATA.SOW_VERSIONS_FAILED",
};
