export const E3T_DATA_TYPE = {
  VALUE_CHANGED: "E3T_DATA_TYPE.VALUE_CHANGED",
  RESOURCE_VALUE_CHANGED: "E3T_DATA_TYPE.RESOURCE_VALUE_CHANGED",
  ADD_RESOURCE_TABLE_ROW: "E3T_DATA_TYPE.ADD_RESOURCE_TABLE_ROW",
  REMOVE_RESOURCE_TABLE_ROW: "E3T_DATA_TYPE.REMOVE_RESOURCE_TABLE_ROW",
  RESOURCE_ROW_CHANGED: "E3T_DATA_TYPE.RESOURCE_ROW_CHANGED",
  RESOURCE_ROW_DEPENDENCY_CHANGED:
    "E3T_DATA_TYPE.RESOURCE_ROW_DEPENDENCY_CHANGED",
  RESOURCE_ROW_SIZING_CHANGED: "E3T_DATA_TYPE.RESOURCE_ROW_SIZING_CHANGED",
  RESET_DATA: "E3T_DATA_TYPE.RESET_DATA",
  RECALCULATE: "E3T_DATA_TYPE.RECALCULATE",
  WORKPACKAGE_COSTING_ESTIMATION:
    "E3T_DATA_TYPE.WORKPACKAGE_COSTING_ESTIMATION",
  WORKPACKAGE_COSTING_ESTIMATION_UPDATE:
    "E3T_DATA_TYPE.WORKPACKAGE_COSTING_ESTIMATION_UPDATE",
  EXPENSES_RECALCULATE: "E3T_DATA_TYPE.EXPENSES_RECALCULATE",
  TOTAL_REMOTE_RESOURCES: "E3T_DATA_TYPE.TOTAL_REMOTE_RESOURCES",
  TOTAL_ONSITE_RESOURCES: "E3T_DATA_TYPE.TOTAL_ONSITE_RESOURCES",
  NEWE3T_REMOTE_CHANGED: "E3T_DATA_TYPE.NEWE3T_REMOTE_CHANGED",
  NEWE3T_SDT_CHANGED: "E3T_DATA_TYPE.NEWE3T_SDT_CHANGED",
  NEWE3T_DEPENDENCY_CHANGED: "E3T_DATA_TYPE.NEWE3T_DEPENDENCY_CHANGED",
  NEW_EGM_AND_FINAL_PRICE: "E3T_DATA_TYPE.NEW_EGM_AND_FINAL_PRICE",
  NEW_E3T_WP_ADD: "E3T_DATA_TYPE.NEW_E3T_WP_ADD",
  RESOURCE_ROW_RISK_RATING_CHANGED:
    "E3T_DATA_TYPE.RESOURCE_ROW_RISK_RATING_CHANGED",
  DISCOUNT_CHANGE: "E3T_DATA_TYPE.DISCOUNT_CHANGE",
  NEW_E3T_CUSTOM_WP_ADDED: "E3T_DATA_TYPE.NEW_E3T_CUSTOM_WP_ADDED",
  NEW_E3T_CUSTOM_WP_RENAME: "E3T_DATA_TYPE.NEW_E3T_CUSTOM_WP_RENAME",
};
