export const MASTER_DATA_ACTION_TYPES = {
  VALUE_CHANGED: "MASTER_DATA_ACTION_TYPES.VALUE_CHANGED",
  MASTER_DATA_RESET: "MASTER_DATA_ACTION_TYPES.MASTER_DATA_RESET",
  MASTER_DATA_OPPID_RESET: "MASTER_DATA_ACTION_TYPES.MASTER_DATA_OPPID_RESET",
  MASTER_DATA_RESET_ALL: "MASTER_DATA_ACTION_TYPES.MASTER_DATA_RESET_ALL",
  MASTER_DATA_RESET_DATA: "MASTER_DATA_ACTION_TYPES.MASTER_DATA_RESET_DATA",
  COUNTRY_DROPDOWN_DATA_FETCHING:
    "MASTER_DATA_ACTION_TYPES.COUNTRY_DROPDOWN_DATA_FETCHING",
  COUNTRY_DROPDOWN_DATA_FETCHED:
    "MASTER_DATA_ACTION_TYPES.COUNTRY_DROPDOWN_DATA_FETCHED",
  COUNTRY_DROPDOWN_DATA_FAILED:
    "MASTER_DATA_ACTION_TYPES.COUNTRY_DROPDOWN_DATA_FAILED",
};
