export const CLONE_SAFE_TYPES = {
  CUSTOMER_DATA_FETCHED: "CLONE_SAFE_TYPES.CUSTOMER_DATA_FETCHED",
  TEMPLATES_FETCHED: "CLONE_SAFE_TYPES.TEMPLATES_FETCHED",
  PRODUCT_LINES_FETCHED: "CLONE_SAFE_TYPES.PRODUCT_LINES_FETCHED",

  RESET_DATA: "CLONE_SAFE_TYPES.RESET_DATA",

  SHOW_MODAL: "CLONE_SAFE_TYPES.SHOW_MODAL",
  CLOSE_MODAL: "CLONE_SAFE_TYPES.CLOSE_MODAL",
  CLONE_BREAK: "CLONE_SAFE_TYPES.CLONE_BREAK",

  SAVE_NEW_PRODUCT_LINE: "CLONE_SAFE_TYPES.SAVE_NEW_PRODUCT_LINE",
  SAVE_NEW_BUSINESS: "CLONE_SAFE_TYPES.SAVE_NEW_BUSINESS",
  SAVE_NEW_TEMPLATE: "CLONE_SAFE_TYPES.SAVE_NEW_TEMPLATE",
};
