export const GENERATE_PREVIEW_TYPE = {
  GENERATE_PREVIEW_POSTING: "GENERATE_PREVIEW_TYPE.GENERATE_PREVIEW_POSTING",
  GENERATE_PREVIEW_POSTED: "GENERATE_PREVIEW_TYPE.GENERATE_PREVIEW_POSTED",
  GENERATE_PREVIEW_POST_FAILED:
    "GENERATE_PREVIEW_TYPE.GENERATE_PREVIEW_POST_FAILED",

  DOWNLOAD_POSTING: "GENERATE_PREVIEW_TYPE.DOWNLOAD_POSTING",
  DOWNLOAD_POSTED: "GENERATE_PREVIEW_TYPE.DOWNLOAD_POSTED",
  DOWNLOAD_POST_FAILED: "GENERATE_PREVIEW_TYPE.DOWNLOAD_POST_FAILED",

  SET_DOWNLOAD_PERCENT: "GENERATE_PREVIEW_TYPE.SET_DOWNLOAD_PERCENT",

  RESET_DATA: "GENERATE_PREVIEW_TYPE.RESET_DATA",
  SAVE_TEMPLATE: "GENERATE_PREVIEW_TYPE.SAVE_TEMPLATE",

  LOAD_PREVIEW: "GENERATE_PREVIEW_TYPE.LOAD_PREVIEW",
};
