const DRAFT_ACTION_TYPES = {
  SAVE_PAGE_DRAFT: "DRAFT_ACTION_TYPES.SAVE_PAGE_DRAFT",
  RESET_DRAFT: "DRAFT_ACTION_TYPES.RESET_DRAFT",
  SAVE_PAGE_DRAFT_SAVING: "DRAFT_ACTION_TYPES.SAVE_PAGE_DRAFT_SAVING",
  SAVE_PAGE_DRAFT_SAVED: "DRAFT_ACTION_TYPES.SAVE_PAGE_DRAFT_SAVED",
  PAGE_DATA_LOADING: "DRAFT_ACTION_TYPES.PAGE_DATA_LOADING",
  PAGE_DATA_LOADED: "DRAFT_ACTION_TYPES.PAGE_DATA_LOADED",
  PAGE_DATA_LOADING_FAILED: "DRAFT_ACTION_TYPES.PAGE_DATA_LOADING_FAILED",
  SAVE_PAGE_DRAFT_SAVING_FAILED:
    "DRAFT_ACTION_TYPES.SAVE_PAGE_DRAFT_SAVING_FAILED",
  SIDE_PANEL_SHOW: "DRAFT_ACTION_TYPES.SIDE_PANEL_SHOW",
  SIDE_PANEL_HIDE: "DRAFT_ACTION_TYPES.SIDE_PANEL_HIDE",
  SIDE_PANEL_DATA_FETCHING: "DRAFT_ACTION_TYPES.SIDE_PANEL_DATA_FETCHING",
  SIDE_PANEL_DATA_FETCHED: "DRAFT_ACTION_TYPES.SIDE_PANEL_DATA_FETCHED",
  SIDE_PANEL_DATA_FETCH_FAILED:
    "DRAFT_ACTION_TYPES.SIDE_PANEL_DATA_FETCH_FAILED",
  RESET_DRAFT_PAGEPOSTDATA: "DRAFT_ACTION_TYPES.RESET_DRAFT_PAGEPOSTDATA",
  DRAFT_LOAD_LATEST: "DRAFT_ACTION_TYPES.DRAFT_LOAD_LATEST",
  DRAFT_NOT_LOAD_LATEST: "DRAFT_ACTION_TYPES.DRAFT_NOT_LOAD_LATEST",
  SIDE_PANEL_DATA_APPEND: "DRAFT_ACTION_TYPES.SIDE_PANEL_DATA_APPEND",
};

export default DRAFT_ACTION_TYPES;
