export const SOW_HISTORY_DATA_TYPE = {
  HISTORY_FETCHING: "SOW_HISTORY_DATA_TYPE.HISTORY_FETCHING",
  HISTORY_FETCHED: "SOW_HISTORY_DATA_TYPE.HISTORY_FETCHED",
  HISTORY_FETCH_FAILED: "SOW_HISTORY_DATA_TYPE.HISTORY_FETCH_FAILED",

  HISTORY_APPEND: "SOW_HISTORY_DATA_TYPE.HISTORY.APPEND",

  PANEL_OPEN: "SOW_HISTORY_DATA_TYPE.PANEL_OPEN",
  PANEL_CLOSE: "SOW_HISTORY_DATA_TYPE.PANEL_CLOSE",
  PANEL_TOGGLE: "SOW_HISTORY_DATA_TYPE.PANEL_TOGGLE",
  SOW_USER_DETAILS_FETCHING: "SOW_HISTORY_DATA_TYPE.SOW_USER_DETAILS_FETCHING",
  SOW_USER_DETAILS_FETCHED: "SOW_HISTORY_DATA_TYPE.SOW_USER_DETAILS_FETCHED",
  SOW_USER_DETAILS_FAILED: "SOW_HISTORY_DATA_TYPE.SOW_USER_DETAILS_FAILED",
  SOW_USER_ROLE: "SOW_HISTORY_DATA_TYPE.SOW_USER_ROLE",
};
