export const SOLUTIONHUB_SIDE_PANEL_DATA_TYPES = {
  PANEL_OPEN: "SOLUTIONHUB_SIDE_PANEL_DATA_TYPES.PANEL_OPEN",
  PANEL_CLOSE: "SOLUTIONHUB_SIDE_PANEL_DATA_TYPES.PANEL_CLOSE",
  PANEL_TOGGLE: "SOLUTIONHUB_SIDE_PANEL_DATA_TYPES.PANEL_TOGGLE",
  SOLUTIONHUB_SIDEPANEL_DATA_FETCHING:
    "SOLUTIONHUB_SIDE_PANEL_DATA_TYPES.SOLUTIONHUB_SIDEPANEL_DATA_FETCHING",
  SOLUTIONHUB_SIDEPANEL_DATA_FETCHED:
    "SOLUTIONHUB_SIDE_PANEL_DATA_TYPES.SOLUTIONHUB_SIDEPANEL_DATA_FETCHED",
  SOLUTIONHUB_SIDEPANEL_DATA_FAILED:
    "SOLUTIONHUB_SIDE_PANEL_DATA_TYPES.SOLUTIONHUB_SIDEPANEL_DATA_FAILED",
  SOLUTIONHUB_SIDEPANEL_DATA_APPEND:
    "SOLUTIONHUB_SIDE_PANEL_DATA_TYPES.SOLUTIONHUB_SIDEPANEL_DATA_APPEND",
};
