export const CUSTOMER_DATA_TYPE = {
  VALUE_CHANGED: "CUSTOMER_DATA_TYPE.VALUE_CHANGED",
  API_DATA_FETCHING: "CUSTOMER_DATA_TYPE.API_DATA_FETCHING",
  API_DATA_FETCHED: "CUSTOMER_DATA_TYPE.API_DATA_FETCHED",
  API_DATA_FAILED: "CUSTOMER_DATA_TYPE.API_DATA_FAILED",
  RESET_DATA: "CUSTOMER_DATA_TYPE.RESET_DATA",
  RESET_SKU: "CUSTOMER_DATA_TYPE.RESET_SKU",
  REMOVE_SKU_INDEX: "CUSTOMER_DATA_TYPE.REMOVE_SKU_INDEX",
  NO_RESPONSE_ERROR_HANDLER: "CUSTOMER_DATA_TYPE.NO_RESPONSE_ERROR_HANDLER",
  ISCLONE: "CUSTOMER_DATA_TYPE.ISCLONE",
};
