export const DYNAMIC_DATA_TYPES = {
  FIELDS_LOADED: "DYNAMIC_DATA_TYPES.FIELDS_LOADED",
  FIELD_VALUE_CHANGED: "DYNAMIC_DATA_TYPES.FIELD_VALUE_CHANGED",
  TABLE_VALUE_CHANGED: "DYNAMIC_DATA_TYPES.TABLE_VALUE_CHANGED",
  TABLE_ROW_ADDED: "DYNAMIC_DATA_TYPES.TABLE_ROW_ADDED",
  TABLE_ROW_REMOVED: "DYNAMIC_DATA_TYPES.TABLE_ROW_REMOVED",
  FIELDS_PAGE_UPDATE: "DYNAMIC_DATA_TYPES.FIELDS_PAGE_UPDATE",
  PAGE_SHOULD_UPDATE: "DYNAMIC_DATA_TYPES.PAGE_SHOULD_UPDATE",
  WORK_PACKAGE_ADD: "DYNAMIC_DATA_TYPES.WORK_PACKAGE_ADD",
  CUSTOM_WORK_PACKAGE_ADD: "DYNAMIC_DATA_TYPES.CUSTOM_WORK_PACKAGE_ADD",
  WORK_PACKAGE_NAME_CHANGED: "DYNAMIC_DATA_TYPES.WORK_PACKAGE_NAME_CHANGED",
  WORK_PACKAGE_REMOVE: "DYNAMIC_DATA_TYPES.WORK_PACKAGE_REMOVE",
  WORK_PACKAGE_UPDATE: "DYNAMIC_DATA_TYPES.WORK_PACKAGE_UPDATE",
  WORK_PACKAGE_UPDATE_END: "DYNAMIC_DATA_TYPES.WORK_PACKAGE_UPDATE_END",
  WORK_PACKAGE_MOVED: "DYNAMIC_DATA_TYPES.WORK_PACKAGE_MOVED",
  FIELDS_RESET: "DYNAMIC_DATA_TYPES.FIELDS_RESET",
  PREDEFINED_PACKAGE_ADDED: "DYNAMIC_DATA_TYPES.PREDEFINED_PACKAGE_ADDED",
  FIELDS_CHANGED: "DYNAMIC_DATA_TYPES.FIELDS_CHANGED",
  PRODUCTLINE_SKU_CHANGED: "DYNAMIC_DATA_TYPES.PRODUCTLINE_SKU_CHANGED",
  SKU_EDIT_UPDATE: "DYNAMIC_DATA_TYPES.SKU_EDIT_UPDATE",
  EDIT_WORK_PACKAGES_INIT: "DYNAMIC_DATA_TYPES.EDIT_WORK_PACKAGES_INIT",
  WORK_PACKAGE_TABLE_UPDATE: "DYNAMIC_DATA_TYPES.WORK_PACKAGE_TABLE_UPDATE",
  WORK_PACKAGE_TABLE_ROW_ADD: "DYNAMIC_DATA_TYPES.WORK_PACKAGE_TABLE_ROW_ADD",
  WORK_PACKAGE_TABLE_ROW_REMOVE:
    "DYNAMIC_DATA_TYPES.WORK_PACKAGE_TABLE_ROW_REMOVE",
  SECTION_DATA_LOADED: "DYNAMIC_DATA_TYPES.SECTION_DATA_LOADED",
  SECTION_DATA_LOADING: "DYNAMIC_DATA_TYPES.SECTION_DATA_LOADING",
  CUSTOM_MODULES_SAVE_UPDATE_FETCHING:
    "DYNAMIC_DATA_TYPES.CUSTOM_MODULES_SAVE_UPDATE_FETCHING",
  CUSTOM_MODULES_SAVE_UPDATE_FETCHED:
    "DYNAMIC_DATA_TYPES.CUSTOM_MODULES_SAVE_UPDATE_FETCHED",
  CUSTOM_MODULES_SAVE_UPDATE_FAILED:
    "DYNAMIC_DATA_TYPES.CUSTOM_MODULES_SAVE_UPDATE_FAILED",
  CUSTOM_MODULES_RENAME: "DYNAMIC_DATA_TYPES.CUSTOM_MODULES_RENAME",
  FIELD_MULTIPLE_VALUE_CHANGED:
    "DYNAMIC_DATA_TYPES.FIELD_MULTIPLE_VALUE_CHANGED",
};
